#ifndef SCENARIO_APP_CO2_PERSON_LORA_SETTINGS_H_
#define SCENARIO_APP_CO2_PERSON_LORA_SETTINGS_H_

constexpr int CO2_THR = 800;
constexpr int PERSON_THR = 5;

#endif // SCENARIO_APP_CO2_PERSON_LORA_SETTINGS_H_